---
title: "Session 6: Homework 3"
author: "Ioana-Daria Gherghelas, Sophia Lyuleva, Sneha Ramteke, Arvind Sridhar, Sihan Lu, Wei Wu"
date: "2022-09-20"
output:
  html_document:
    theme: flatly
    highlight: zenburn
    number_sections: yes
    toc: yes
    toc_float: yes
    code_folding: show
---



<div id="youth-risk-behavior-surveillance" class="section level1">
<h1>Youth Risk Behavior Surveillance</h1>
<p>Every two years, the Centers for Disease Control and Prevention conduct the <a href="https://www.cdc.gov/healthyyouth/data/yrbs/index.htm">Youth Risk Behavior Surveillance System (YRBSS)</a> survey, where it takes data from high schoolers (9th through 12th grade), to analyze health patterns. You will work with a selected group of variables from a random sample of observations during one of the years the YRBSS was conducted.</p>
<div id="load-the-data" class="section level2">
<h2>Load the data</h2>
<p>This data is part of the <code>openintro</code> textbook and we can load and inspect it. There are observations on 13 different variables, some categorical and some numerical. The meaning of each variable can be found by bringing up the help file:</p>
<p>?yrbss</p>
<pre class="r"><code>data(yrbss)
glimpse(yrbss)</code></pre>
<pre><code>## Rows: 13,583
## Columns: 13
## $ age                      &lt;int&gt; 14, 14, 15, 15, 15, 15, 15, 14, 15, 15, 15, 1…
## $ gender                   &lt;chr&gt; &quot;female&quot;, &quot;female&quot;, &quot;female&quot;, &quot;female&quot;, &quot;fema…
## $ grade                    &lt;chr&gt; &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, …
## $ hispanic                 &lt;chr&gt; &quot;not&quot;, &quot;not&quot;, &quot;hispanic&quot;, &quot;not&quot;, &quot;not&quot;, &quot;not&quot;…
## $ race                     &lt;chr&gt; &quot;Black or African American&quot;, &quot;Black or Africa…
## $ height                   &lt;dbl&gt; NA, NA, 1.73, 1.60, 1.50, 1.57, 1.65, 1.88, 1…
## $ weight                   &lt;dbl&gt; NA, NA, 84.4, 55.8, 46.7, 67.1, 131.5, 71.2, …
## $ helmet_12m               &lt;chr&gt; &quot;never&quot;, &quot;never&quot;, &quot;never&quot;, &quot;never&quot;, &quot;did not …
## $ text_while_driving_30d   &lt;chr&gt; &quot;0&quot;, NA, &quot;30&quot;, &quot;0&quot;, &quot;did not drive&quot;, &quot;did not…
## $ physically_active_7d     &lt;int&gt; 4, 2, 7, 0, 2, 1, 4, 4, 5, 0, 0, 0, 4, 7, 7, …
## $ hours_tv_per_school_day  &lt;chr&gt; &quot;5+&quot;, &quot;5+&quot;, &quot;5+&quot;, &quot;2&quot;, &quot;3&quot;, &quot;5+&quot;, &quot;5+&quot;, &quot;5+&quot;,…
## $ strength_training_7d     &lt;int&gt; 0, 0, 0, 0, 1, 0, 2, 0, 3, 0, 3, 0, 0, 7, 7, …
## $ school_night_hours_sleep &lt;chr&gt; &quot;8&quot;, &quot;6&quot;, &quot;&lt;5&quot;, &quot;6&quot;, &quot;9&quot;, &quot;8&quot;, &quot;9&quot;, &quot;6&quot;, &quot;&lt;5&quot;…</code></pre>
<p>Before you carry on with your analysis, it’s is always a good idea to check with <code>skimr::skim()</code> to get a feel for missing values, summary statistics of numerical variables, and a very rough histogram.</p>
</div>
<div id="exploratory-data-analysis" class="section level2">
<h2>Exploratory Data Analysis</h2>
<p>You will first start with analyzing the <code>weight</code> of participants in kilograms. Using visualization and summary statistics, describe the distribution of weights. How many observations are we missing weights from?</p>
<pre class="r"><code>plot1 &lt;- yrbss %&gt;%
  ggplot(aes(x=weight)) + 
  geom_histogram() + labs(x=&quot;Distibution of Weights&quot;,y=&quot;Count&quot;,title=&quot;Histogram of DIstribution of Weights&quot;)
plot1</code></pre>
<p><img src="/blogs/homework3_files/figure-html/eda_on_weight-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>summary(yrbss)  #finding the summary of the data to understand the mean, median, quartiles min,max and NA&#39;s</code></pre>
<pre><code>##       age          gender             grade             hispanic        
##  Min.   :12.0   Length:13583       Length:13583       Length:13583      
##  1st Qu.:15.0   Class :character   Class :character   Class :character  
##  Median :16.0   Mode  :character   Mode  :character   Mode  :character  
##  Mean   :16.2                                                           
##  3rd Qu.:17.0                                                           
##  Max.   :18.0                                                           
##  NA&#39;s   :77                                                             
##      race               height         weight      helmet_12m       
##  Length:13583       Min.   :1      Min.   : 30    Length:13583      
##  Class :character   1st Qu.:2      1st Qu.: 56    Class :character  
##  Mode  :character   Median :2      Median : 64    Mode  :character  
##                     Mean   :2      Mean   : 68                      
##                     3rd Qu.:2      3rd Qu.: 76                      
##                     Max.   :2      Max.   :181                      
##                     NA&#39;s   :1004   NA&#39;s   :1004                     
##  text_while_driving_30d physically_active_7d hours_tv_per_school_day
##  Length:13583           Min.   :0.0          Length:13583           
##  Class :character       1st Qu.:2.0          Class :character       
##  Mode  :character       Median :4.0          Mode  :character       
##                         Mean   :3.9                                 
##                         3rd Qu.:7.0                                 
##                         Max.   :7.0                                 
##                         NA&#39;s   :273                                 
##  strength_training_7d school_night_hours_sleep
##  Min.   :0            Length:13583            
##  1st Qu.:0            Class :character        
##  Median :3            Mode  :character        
##  Mean   :3                                    
##  3rd Qu.:5                                    
##  Max.   :7                                    
##  NA&#39;s   :1176</code></pre>
<pre class="r"><code>sum(is.na(yrbss$weight))   #code to calculate the number of NA&#39;s</code></pre>
<pre><code>## [1] 1004</code></pre>
<p>We are missing weights from 1004 observations, which is roughly 7.5% of observations.</p>
<p>Next, consider the possible relationship between a high schooler’s weight and their physical activity. Plotting the data is a useful first step because it helps us quickly visualize trends, identify strong associations, and develop research questions.</p>
<pre class="r"><code>plot1 &lt;- ggplot(yrbss,aes(y=weight,x=physically_active_7d))+geom_point() +geom_smooth(method=&quot;lm&quot;)
plot1   #plot to find the relationship between a high schoolers weight and their physical activity</code></pre>
<p><img src="/blogs/homework3_files/figure-html/plot-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>yrbss %&gt;% 
  select(physically_active_7d, weight) %&gt;% 
  cor(use = &quot;complete.obs&quot;) #comparing the same with the corr value to cross check if a correlation exists</code></pre>
<pre><code>##                      physically_active_7d weight
## physically_active_7d               1.0000 0.0481
## weight                             0.0481 1.0000</code></pre>
<p>Let’s create a new variable in the dataframe <code>yrbss</code>, called <code>physical_3plus</code> , which will be <code>yes</code> if they are physically active for at least 3 days a week, and <code>no</code> otherwise. You may also want to calculate the number and % of those who are and are not active for more than 3 days. RUse the <code>count()</code> function and see if you get the same results as <code>group_by()... summarise()</code></p>
<pre class="r"><code>physical_3plus &lt;- yrbss %&gt;%
  count(physically_active_7d&gt;=3)
physical_3plus     #using count </code></pre>
<pre><code>## # A tibble: 3 × 2
##   `physically_active_7d &gt;= 3`     n
##   &lt;lgl&gt;                       &lt;int&gt;
## 1 FALSE                        4404
## 2 TRUE                         8906
## 3 NA                            273</code></pre>
<pre class="r"><code>physical_3 &lt;- yrbss %&gt;%
  group_by(physically_active_7d) %&gt;% 
  summarise(physically_active=sum(count(physically_active_7d&gt;=3))) %&gt;% 
  summarise(total_active = sum(physically_active)) 
physical_3   #using group_by and summarise</code></pre>
<pre><code>## # A tibble: 1 × 1
##   total_active
##          &lt;int&gt;
## 1         8906</code></pre>
<p>Can you provide a 95% confidence interval for the population proportion of high schools that are <em>NOT</em> active 3 or more days per week?</p>
<pre class="r"><code>data1 &lt;- yrbss %&gt;%
  filter(physically_active_7d&lt;3)
data1  </code></pre>
<pre><code>## # A tibble: 4,404 × 13
##      age gender grade hispanic race        height weight helme…¹ text_…² physi…³
##    &lt;int&gt; &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;    &lt;chr&gt;        &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;     &lt;int&gt;
##  1    14 female 9     not      Black or A…  NA      NA   never   &lt;NA&gt;          2
##  2    15 female 9     not      Black or A…   1.6    55.8 never   0             0
##  3    15 female 9     not      Black or A…   1.5    46.7 did no… did no…       2
##  4    15 female 9     not      Black or A…   1.57   67.1 did no… did no…       1
##  5    15 male   10    not      Black or A…   1.37   97.1 did no… &lt;NA&gt;          0
##  6    15 female 9     not      Black or A…   1.68   69.8 did no… 0             0
##  7    15 female 9     not      Black or A…   1.65   66.7 did no… did no…       0
##  8    16 male   9     not      Black or A…   1.83   73.5 never   did no…       0
##  9    16 female 10    not      Black or A…   1.55   52.2 did no… 0             2
## 10    15 female 10    not      Black or A…  NA      NA   did no… did no…       2
## # … with 4,394 more rows, 3 more variables: hours_tv_per_school_day &lt;chr&gt;,
## #   strength_training_7d &lt;int&gt;, school_night_hours_sleep &lt;chr&gt;, and abbreviated
## #   variable names ¹​helmet_12m, ²​text_while_driving_30d, ³​physically_active_7d</code></pre>
<pre class="r"><code>n &lt;- count(data1)
xbar &lt;- mean(data1$physically_active_7d,na.rm=TRUE)
s &lt;- sd(data1$physically_active_7d,na.rm=TRUE)
margin &lt;- qt(0.975,as.integer(n-1))*s/sqrt(n)
lower_interval &lt;- xbar-margin
upper_interval &lt;- xbar+margin</code></pre>
<p>Make a boxplot of <code>physical_3plus</code> vs. <code>weight</code>. Is there a relationship between these two variables? What did you expect and why?</p>
<pre class="r"><code>physical_3plus &lt;- yrbss %&gt;%
  mutate(final_result = ifelse(physically_active_7d&gt;=3,&#39;yes&#39;,&#39;no&#39;)) %&gt;% 
drop_na(final_result)
physical_3plus  </code></pre>
<pre><code>## # A tibble: 13,310 × 14
##      age gender grade hispanic race        height weight helme…¹ text_…² physi…³
##    &lt;int&gt; &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;    &lt;chr&gt;        &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;     &lt;int&gt;
##  1    14 female 9     not      Black or A…  NA      NA   never   0             4
##  2    14 female 9     not      Black or A…  NA      NA   never   &lt;NA&gt;          2
##  3    15 female 9     hispanic Native Haw…   1.73   84.4 never   30            7
##  4    15 female 9     not      Black or A…   1.6    55.8 never   0             0
##  5    15 female 9     not      Black or A…   1.5    46.7 did no… did no…       2
##  6    15 female 9     not      Black or A…   1.57   67.1 did no… did no…       1
##  7    15 female 9     not      Black or A…   1.65  132.  did no… &lt;NA&gt;          4
##  8    14 male   9     not      Black or A…   1.88   71.2 never   &lt;NA&gt;          4
##  9    15 male   9     not      Black or A…   1.75   63.5 never   &lt;NA&gt;          5
## 10    15 male   10    not      Black or A…   1.37   97.1 did no… &lt;NA&gt;          0
## # … with 13,300 more rows, 4 more variables: hours_tv_per_school_day &lt;chr&gt;,
## #   strength_training_7d &lt;int&gt;, school_night_hours_sleep &lt;chr&gt;,
## #   final_result &lt;chr&gt;, and abbreviated variable names ¹​helmet_12m,
## #   ²​text_while_driving_30d, ³​physically_active_7d</code></pre>
<pre class="r"><code>plot1 &lt;- ggplot(physical_3plus,aes(x=final_result, y=weight)) + 
  geom_boxplot()
plot1</code></pre>
<p><img src="/blogs/homework3_files/figure-html/boxplot-1.png" width="648" style="display: block; margin: auto;" /></p>
<blockquote>
<p>From the boxplot we can see that there is no relation between physical3plus and weight. We expected to have no relation between these two variables as we already performed a corr test and found the value close 0.</p>
</blockquote>
</div>
<div id="confidence-interval" class="section level2">
<h2>Confidence Interval</h2>
<p>Boxplots show how the medians of the two distributions compare, but we can also compare the means of the distributions using either a confidence interval or a hypothesis test. Note that when we calculate the mean, SD, etc. weight in these groups using the mean function, we must ignore any missing values by setting the <code>na.rm = TRUE</code>.</p>
<pre class="r"><code>physical_3plus %&gt;% 
  select(weight,final_result) %&gt;% 
  drop_na(weight,final_result) %&gt;% 
  group_by(final_result) %&gt;% 
  summarise(count = n(),
            xbar = mean(weight),
            s=sd(weight),
            margin = qt(0.975,count-1),
            lower_interval = xbar-margin,
            upper_interval = xbar+margin)</code></pre>
<pre><code>## # A tibble: 2 × 7
##   final_result count  xbar     s margin lower_interval upper_interval
##   &lt;chr&gt;        &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;          &lt;dbl&gt;          &lt;dbl&gt;
## 1 no            4022  66.7  17.6   1.96           64.7           68.6
## 2 yes           8342  68.4  16.5   1.96           66.5           70.4</code></pre>
<p>There is an observed difference of about 1.77kg (68.44 - 66.67), and we notice that the two confidence intervals do not overlap. It seems that the difference is at least 95% statistically significant. Let us also conduct a hypothesis test.</p>
</div>
<div id="hypothesis-test-with-formula" class="section level2">
<h2>Hypothesis test with formula</h2>
<p>Write the null and alternative hypotheses for testing whether mean weights are different for those who exercise at least times a week and those who don’t.</p>
<pre class="r"><code>t.test(weight ~ final_result, data = physical_3plus)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  weight by final_result
## t = -5, df = 7479, p-value = 9e-08
## alternative hypothesis: true difference in means between group no and group yes is not equal to 0
## 95 percent confidence interval:
##  -2.42 -1.12
## sample estimates:
##  mean in group no mean in group yes 
##              66.7              68.4</code></pre>
<blockquote>
<p>Null Hypothesis: mean weights are same for those who exercise at least 3 times a week and those who don’t.
Alternative Hypothesis: mean weights are different for those who exercise at least 3 times a week and those who don’t
t test value is greater than 2 and 95% confidence interval does not contain 0 hence we reject the null hypothesis. So, mean weights are different for those who exercise at least 3 times a week and those who don’t.</p>
</blockquote>
</div>
<div id="hypothesis-test-with-infer" class="section level2">
<h2>Hypothesis test with <code>infer</code></h2>
<p>Next, we will introduce a new function, <code>hypothesize</code>, that falls into the infer workflow. You will use this method for conducting hypothesis tests.</p>
<p>But first, we need to initialize the test, which we will save as <code>obs_diff</code>.</p>
<pre class="r"><code>obs_diff &lt;- physical_3plus %&gt;%
  drop_na(weight,final_result) %&gt;% 
  specify(weight ~ final_result) %&gt;%
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;yes&quot;, &quot;no&quot;))
obs_diff</code></pre>
<pre><code>## Response: weight (numeric)
## Explanatory: final_result (factor)
## # A tibble: 1 × 1
##    stat
##   &lt;dbl&gt;
## 1  1.77</code></pre>
<p>Notice how you can use the functions specify and calculate again like you did for calculating confidence intervals. Here, though, the statistic you are searching for is the difference in means, with the order being yes - no != 0.</p>
<p>After you have initialized the test, you need to simulate the test on the null distribution, which we will save as null.</p>
<pre class="r"><code>set.seed(1234) 
null_dist &lt;- physical_3plus %&gt;%
  drop_na(weight,final_result) %&gt;% 
  # specify variables
  specify(weight ~ final_result) %&gt;%
  
  # assume independence, i.e, there is no difference
  hypothesize(null = &quot;independence&quot;) %&gt;%
  
  # generate 1000 reps, of type &quot;permute&quot;
  generate(reps = 1000, type = &quot;permute&quot;) %&gt;%
  
  # calculate statistic of difference, namely &quot;diff in means&quot;
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;yes&quot;, &quot;no&quot;))</code></pre>
<p>Here, <code>hypothesize</code> is used to set the null hypothesis as a test for independence, i.e., that there is no difference between the two population means. In one sample cases, the null argument can be set to <em>point</em> to test a hypothesis relative to a point estimate.</p>
<p>Also, note that the <code>type</code> argument within generate is set to permute, which is the argument when generating a null distribution for a hypothesis test.</p>
<p>We can visualize this null distribution with the following code:</p>
<pre class="r"><code>ggplot(data = null_dist, aes(x = stat)) +
  geom_histogram()</code></pre>
<p><img src="/blogs/homework3_files/figure-html/unnamed-chunk-4-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>Now that the test is initialized and the null distribution formed, we can visualise to see how many of these null permutations have a difference of at least <code>obs_stat</code> of 1.77?</p>
<p>We can also calculate the p-value for your hypothesis test using the function <code>infer::get_p_value()</code>.</p>
<pre class="r"><code>null_dist %&gt;% visualize() +
  shade_p_value(obs_stat = obs_diff, direction = &quot;two-sided&quot;)</code></pre>
<p><img src="/blogs/homework3_files/figure-html/unnamed-chunk-5-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>null_dist %&gt;%
  get_p_value(obs_stat = obs_diff, direction = &quot;two_sided&quot;)</code></pre>
<pre><code>## # A tibble: 1 × 1
##   p_value
##     &lt;dbl&gt;
## 1       0</code></pre>
<p>This the standard workflow for performing hypothesis tests.</p>
</div>
</div>
<div id="imdb-ratings-differences-between-directors" class="section level1">
<h1>IMDB ratings: Differences between directors</h1>
<p>Recall the IMBD ratings data. I would like you to explore whether the mean IMDB rating for Steven Spielberg and Tim Burton are the same or not. I have already calculated the confidence intervals for the mean ratings of these two directors and as you can see they overlap.</p>
<p>First, I would like you to reproduce this graph. You may find <code>geom_errorbar()</code> and <code>geom_rect()</code> useful.</p>
<p>In addition, you will run a hpothesis test. You should use both the <code>t.test</code> command and the <code>infer</code> package to simulate from a null distribution, where you assume zero difference between the two.</p>
<blockquote>
<p>Before anything, write down the null and alternative hypotheses, as well as the resulting test statistic and the associated t-stat or p-value. At the end of the day, what do you conclude?</p>
</blockquote>
<p>You can load the data and examine its structure</p>
<pre class="r"><code>movies &lt;- read_csv(here::here(&quot;data&quot;, &quot;movies.csv&quot;))
glimpse(movies)</code></pre>
<pre><code>## Rows: 2,961
## Columns: 11
## $ title               &lt;chr&gt; &quot;Avatar&quot;, &quot;Titanic&quot;, &quot;Jurassic World&quot;, &quot;The Avenge…
## $ genre               &lt;chr&gt; &quot;Action&quot;, &quot;Drama&quot;, &quot;Action&quot;, &quot;Action&quot;, &quot;Action&quot;, &quot;…
## $ director            &lt;chr&gt; &quot;James Cameron&quot;, &quot;James Cameron&quot;, &quot;Colin Trevorrow…
## $ year                &lt;dbl&gt; 2009, 1997, 2015, 2012, 2008, 1999, 1977, 2015, 20…
## $ duration            &lt;dbl&gt; 178, 194, 124, 173, 152, 136, 125, 141, 164, 93, 1…
## $ gross               &lt;dbl&gt; 7.61e+08, 6.59e+08, 6.52e+08, 6.23e+08, 5.33e+08, …
## $ budget              &lt;dbl&gt; 2.37e+08, 2.00e+08, 1.50e+08, 2.20e+08, 1.85e+08, …
## $ cast_facebook_likes &lt;dbl&gt; 4834, 45223, 8458, 87697, 57802, 37723, 13485, 920…
## $ votes               &lt;dbl&gt; 886204, 793059, 418214, 995415, 1676169, 534658, 9…
## $ reviews             &lt;dbl&gt; 3777, 2843, 1934, 2425, 5312, 3917, 1752, 1752, 35…
## $ rating              &lt;dbl&gt; 7.9, 7.7, 7.0, 8.1, 9.0, 6.5, 8.7, 7.5, 8.5, 7.2, …</code></pre>
<p>Your R code and analysis should go here. If you want to insert a blank chunk of R code you can just hit <code>Ctrl/Cmd+Alt+I</code></p>
<pre class="r"><code>select_director = c(&#39;Steven Spielberg&#39;, &#39;Tim Burton&#39;)
director_interval &lt;- movies %&gt;% 
              # filter by interval
              filter(director %in% select_director) %&gt;% 
              group_by(director) %&gt;% 
              # calculate summary statistics for ratings
              summarize(mean_rating = mean(rating, na.rm=TRUE),
                        sd_rating = sd(rating, na.rm=TRUE),
                        count = n(),
                        t_critical = qt(0.975, count - 1),
                        se_rating = sd_rating/sqrt(count),
                        error_margin = t_critical*se_rating,
                        rating_low = mean_rating - error_margin,
                        rating_high = mean_rating + error_margin) %&gt;% 
              select(director, mean_rating, rating_low, rating_high)

director_interval </code></pre>
<pre><code>## # A tibble: 2 × 4
##   director         mean_rating rating_low rating_high
##   &lt;chr&gt;                  &lt;dbl&gt;      &lt;dbl&gt;       &lt;dbl&gt;
## 1 Steven Spielberg        7.57       7.27        7.87
## 2 Tim Burton              6.93       6.53        7.33</code></pre>
<pre class="r"><code>xmin_steven &lt;- director_interval %&gt;% 
               filter(director == &#39;Steven Spielberg&#39;) %&gt;%
               select(rating_low) %&gt;% 
               pull()

xmax_tim &lt;- director_interval %&gt;% 
               filter(director == &#39;Tim Burton&#39;) %&gt;%
               select(rating_high) %&gt;% 
               pull()
               
  
plot_ &lt;- director_interval %&gt;% 
         ggplot(aes(mean_rating, director, colour = director)) + 
         geom_point() +
         geom_errorbarh(aes(xmin = rating_low, xmax = rating_high, y = director), width = 0.2, height = 0.2) + 
         labs(y = &quot;Mean IMDB Rating&quot;) +
         geom_rect(aes(xmin = xmin_steven, xmax = xmax_tim, ymin = -Inf, ymax = Inf),
            alpha = 1/5, fill = &quot;grey&quot;, colour = NA) + 
         theme_bw() +
         theme(legend.position = &quot;none&quot;)

plot_</code></pre>
<p><img src="/blogs/homework3_files/figure-html/confidence_intervals%20for%20steven%20and%20tim-1.png" width="648" style="display: block; margin: auto;" /></p>
<blockquote>
<p>Null Hypothesis: The mean IMDB rating for Steven Spielberg and Tim Burton are the same.
Alternative Hypothesis: The mean IMDB rating for Steven Spielberg and Tim Burton are not the same.</p>
</blockquote>
<pre class="r"><code>select_director = c(&#39;Steven Spielberg&#39;, &#39;Tim Burton&#39;)
movies_select &lt;- movies %&gt;% 
                 filter(director %in% select_director)
mosaic::favstats(~rating, data = movies_select)</code></pre>
<pre><code>##  min  Q1 median  Q3 max mean    sd  n missing
##  5.7 6.7    7.4 7.9 8.9 7.31 0.777 39       0</code></pre>
<pre class="r"><code>mosaic::favstats(rating~director, data = movies_select)</code></pre>
<pre><code>##           director min   Q1 median   Q3 max mean    sd  n missing
## 1 Steven Spielberg 6.2 7.20    7.6 8.00 8.9 7.57 0.695 23       0
## 2       Tim Burton 5.7 6.45    7.0 7.53 8.0 6.93 0.749 16       0</code></pre>
<pre class="r"><code>t.test(rating~director, data = movies_select)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  rating by director
## t = 3, df = 31, p-value = 0.01
## alternative hypothesis: true difference in means between group Steven Spielberg and group Tim Burton is not equal to 0
## 95 percent confidence interval:
##  0.16 1.13
## sample estimates:
## mean in group Steven Spielberg       mean in group Tim Burton 
##                           7.57                           6.93</code></pre>
<blockquote>
<p>From the t-test, we can conclude that the mean IMDB rating for Steven Spielberg and Tim Burton are not the same. This is because t value is greater than 2 (=3) and 95% confidence interval does not contain 0. Also the pvalue is 0.01 which is less than 5% further supporting our conclusion.</p>
</blockquote>
<pre class="r"><code>set.seed(1234)
ratings_director &lt;- movies_select %&gt;%
                        # Specify the variable of interest
                        specify(rating ~ director) %&gt;%
                        # Hypothesize a null of no (or zero) difference
                        hypothesize(null = &quot;independence&quot;) %&gt;%
                        # Generate a bunch of simulated samples
                        generate(reps = 1000, type =&quot;permute&quot;) %&gt;%
                        # Find the mean difference of each sample
                        calculate(stat = &quot;diff in means&quot;,
                        order = c(&#39;Steven Spielberg&#39;, &#39;Tim Burton&#39;))

steven_mean &lt;- director_interval %&gt;% 
               filter(director == &#39;Steven Spielberg&#39;) %&gt;%
               select(mean_rating) %&gt;% 
               pull()

tim_mean &lt;- director_interval %&gt;% 
               filter(director == &#39;Tim Burton&#39;) %&gt;%
               select(mean_rating) %&gt;% 
               pull()
observed_difference &lt;- steven_mean - tim_mean
ratings_director %&gt;% get_pvalue(obs_stat = observed_difference, direction = &quot;both&quot;)</code></pre>
<pre><code>## # A tibble: 1 × 1
##   p_value
##     &lt;dbl&gt;
## 1   0.008</code></pre>
<pre class="r"><code>ratings_director %&gt;% visualize() +
                     annotate(&quot;rect&quot;, xmin = -Inf, xmax = -1*observed_difference, ymin = -Inf, ymax = Inf,
                              alpha = 0.2, fill = &quot;red&quot;, colour = NA) +
                     annotate(&quot;rect&quot;, xmin = 1*observed_difference, xmax = Inf, ymin = -Inf, ymax = Inf,
                              alpha = 0.2, fill = &quot;red&quot;, colour = NA) + 
                     geom_vline(xintercept = observed_difference, alpha = 0.75, colour = &#39;red&#39;, size = 2) +
                     labs(x = &quot;Average steven - tim IMDB rating&quot;, y = &quot;Count&quot;, 
                          title = &quot;Differences in steven and tim average IMDB ratings&quot;,
                          subtitle = &quot;Observed difference in red&quot;) +
                     theme_bw()</code></pre>
<p><img src="/blogs/homework3_files/figure-html/HT_infer-1.png" width="648" style="display: block; margin: auto;" /></p>
<blockquote>
<p>The pvalue in this case is 0.008 which is less than 5%, hence we can conclude that the mean IMDB rating for Steven Spielberg and Tim Burton are not the same.</p>
</blockquote>
</div>
<div id="omega-group-plc--pay-discrimination" class="section level1">
<h1>Omega Group plc- Pay Discrimination</h1>
<p>At the last board meeting of Omega Group Plc., the headquarters of a large multinational company, the issue was raised that women were being discriminated in the company, in the sense that the salaries were not the same for male and female executives. A quick analysis of a sample of 50 employees (of which 24 men and 26 women) revealed that the average salary for men was about 8,700 higher than for women. This seemed like a considerable difference, so it was decided that a further analysis of the company salaries was warranted.</p>
<p>You are asked to carry out the analysis. The objective is to find out whether there is indeed a significant difference between the salaries of men and women, and whether the difference is due to discrimination or whether it is based on another, possibly valid, determining factor.</p>
<div id="loading-the-data" class="section level2">
<h2>Loading the data</h2>
<pre class="r"><code>omega &lt;- read_csv(here::here(&quot;data&quot;, &quot;omega.csv&quot;))
glimpse(omega) # examine the data frame</code></pre>
<pre><code>## Rows: 50
## Columns: 3
## $ salary     &lt;dbl&gt; 81894, 69517, 68589, 74881, 65598, 76840, 78800, 70033, 635…
## $ gender     &lt;chr&gt; &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;ma…
## $ experience &lt;dbl&gt; 16, 25, 15, 33, 16, 19, 32, 34, 1, 44, 7, 14, 33, 19, 24, 3…</code></pre>
</div>
<div id="relationship-salary---gender" class="section level2">
<h2>Relationship Salary - Gender ?</h2>
<p>The data frame <code>omega</code> contains the salaries for the sample of 50 executives in the company. Can you conclude that there is a significant difference between the salaries of the male and female executives?</p>
<p>Note that you can perform different types of analyses, and check whether they all lead to the same conclusion</p>
<p>. Confidence intervals
. Hypothesis testing
. Correlation analysis
. Regression</p>
<pre class="r"><code># Confidence interval and hypothesis testing
t.test(omega %&gt;% 
         filter (gender == &#39;male&#39;) %&gt;%
         select (salary), 
      omega %&gt;%
      filter (gender == &#39;female&#39;) %&gt;%
      select (salary))</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  omega %&gt;% filter(gender == &quot;male&quot;) %&gt;% select(salary) and omega %&gt;% filter(gender == &quot;female&quot;) %&gt;% select(salary)
## t = 4, df = 48, p-value = 2e-04
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##   4420 12973
## sample estimates:
## mean of x mean of y 
##     73239     64543</code></pre>
<blockquote>
<p>The p-value is close to 0, so we reject the null hypothesis, which means that we have strong evidence that mean salaries for men and women are different.
Also, confidence interval does not include 0, which again indicates that mean salaries between men and women are different.</p>
</blockquote>
<pre class="r"><code># Correlation analysis
omega_num &lt;- omega %&gt;% 
mutate(gender_01 = ifelse(gender==&#39;male&#39;, 1, 0)) %&gt;% # convert gender to numerical variable
select(gender_01, salary) %&gt;% # select certain columns
cor()

omega_num</code></pre>
<pre><code>##           gender_01 salary
## gender_01     1.000  0.508
## salary        0.508  1.000</code></pre>
<blockquote>
<p>Correlation coefficient is 0.508 indicates weak correlation between gender and salary.</p>
</blockquote>
<pre class="r"><code># Regression
lm_omega &lt;- lm(formula = salary ~ gender, data = omega) # run a linear regression of salary on gender
summary(lm_omega)</code></pre>
<pre><code>## 
## Call:
## lm(formula = salary ~ gender, data = omega)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -18471  -4780    127   5484  14257 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    64543       1474   43.78  &lt; 2e-16 ***
## gendermale      8696       2128    4.09  0.00017 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 7520 on 48 degrees of freedom
## Multiple R-squared:  0.258,  Adjusted R-squared:  0.243 
## F-statistic: 16.7 on 1 and 48 DF,  p-value: 0.000165</code></pre>
<blockquote>
<p>R-squared is 0.258 (which is exactly correlation coefficient squared), which indicates that only 25% of variation in salary is explained by gender. Also, gendermale ciefficient is statistically significant.
Overall, we can say that there is evidence of correlation between gender and salary.</p>
</blockquote>
<p>Calculate summary statistics on salary by gender. Also, create and print a dataframe where, for each gender, you show the mean, SD, sample size, the t-critical, the SE, the margin of error, and the low/high endpoints of a 95% condifence interval</p>
<pre class="r"><code># Summary Statistics of salary by gender
summary_stats &lt;- mosaic::favstats (salary ~ gender, data=omega)
summary_stats</code></pre>
<pre><code>##   gender   min    Q1 median    Q3   max  mean   sd  n missing
## 1 female 47033 60338  64618 70033 78800 64543 7567 26       0
## 2   male 54768 68331  74675 78568 84576 73239 7463 24       0</code></pre>
<pre class="r"><code># Dataframe with two rows (male-female) and having as columns gender, mean, SD, sample size, 
# the t-critical value, the standard error, the margin of error, 
# and the low/high endpoints of a 95% condifence interval

summary_stats %&gt;%
  mutate(t_crit = qt(0.95, df=n-1), std_err = sd/sqrt(n), margin_err=t_crit*sd/sqrt(n), low_end=mean-margin_err, high_end=mean+margin_err) %&gt;%
  select(gender, mean, sd, n, t_crit, std_err, margin_err, low_end, high_end)</code></pre>
<pre><code>##   gender  mean   sd  n t_crit std_err margin_err low_end high_end
## 1 female 64543 7567 26   1.71    1484       2535   62008    67078
## 2   male 73239 7463 24   1.71    1523       2611   70628    75850</code></pre>
<blockquote>
<p>What can you conclude from your analysis? A couple of sentences would be enough
Confidence intervals do not overlap, so we have strong evidence that mean salaries for men and women are different.</p>
</blockquote>
<p>You can also run a hypothesis testing, assuming as a null hypothesis that the mean difference in salaries is zero, or that, on average, men and women make the same amount of money. You should tun your hypothesis testing using <code>t.test()</code> and with the simulation method from the <code>infer</code> package.</p>
<pre class="r"><code># hypothesis testing using t.test() 
t.test(omega %&gt;% 
         filter (gender == &#39;female&#39;) %&gt;%
         select (salary), 
      omega %&gt;%
        filter (gender == &#39;male&#39;) %&gt;%
        select (salary))</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  omega %&gt;% filter(gender == &quot;female&quot;) %&gt;% select(salary) and omega %&gt;% filter(gender == &quot;male&quot;) %&gt;% select(salary)
## t = -4, df = 48, p-value = 2e-04
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -12973  -4420
## sample estimates:
## mean of x mean of y 
##     64543     73239</code></pre>
<pre class="r"><code># hypothesis testing using infer package
t_test(
  omega,
  formula =  salary ~ gender
)</code></pre>
<pre><code>## # A tibble: 1 × 7
##   statistic  t_df  p_value alternative estimate lower_ci upper_ci
##       &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;          &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1     -4.09  47.8 0.000165 two.sided     -8696.  -12973.   -4420.</code></pre>
<blockquote>
<p>What can you conclude from your analysis? A couple of sentences would be enough
The p-values are less then 0.01, which indicates that there is strong evidence that mean salaries for women and men are different. The confidence interval for the mean is (-12973, -4420).</p>
</blockquote>
</div>
<div id="relationship-experience---gender" class="section level2">
<h2>Relationship Experience - Gender?</h2>
<p>At the board meeting, someone raised the issue that there was indeed a substantial difference between male and female salaries, but that this was attributable to other reasons such as differences in experience. A questionnaire send out to the 50 executives in the sample reveals that the average experience of the men is approximately 21 years, whereas the women only have about 7 years experience on average (see table below).</p>
<pre class="r"><code># Summary Statistics of salary by gender
favstats (experience ~ gender, data=omega)</code></pre>
<pre><code>##   gender min    Q1 median   Q3 max  mean    sd  n missing
## 1 female   0  0.25    3.0 14.0  29  7.38  8.51 26       0
## 2   male   1 15.75   19.5 31.2  44 21.12 10.92 24       0</code></pre>
<p>Based on this evidence, can you conclude that there is a significant difference between the experience of the male and female executives? Perform similar analyses as in the previous section. Does your conclusion validate or endanger your conclusion about the difference in male and female salaries?</p>
<p>The standard deviation is pretty high, so we should definitely perform additional analyses to make a conclusion.</p>
<pre class="r"><code># Confidence interval and hypothesis testing
t.test(omega %&gt;% 
         filter (gender == &#39;male&#39;) %&gt;%
         select (experience), 
      omega %&gt;%
      filter (gender == &#39;female&#39;) %&gt;%
      select (experience))</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  omega %&gt;% filter(gender == &quot;male&quot;) %&gt;% select(experience) and omega %&gt;% filter(gender == &quot;female&quot;) %&gt;% select(experience)
## t = 5, df = 43, p-value = 1e-05
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##   8.13 19.35
## sample estimates:
## mean of x mean of y 
##     21.12      7.38</code></pre>
<p>The p-value is close to 0, so we reject the null hypothesis, which means that we have strong evidence that mean experience for men and women are different.</p>
<p>Just as in case of salary, confidence interval does not include 0, which again indicates different mean experience for men and women.</p>
<pre class="r"><code># Correlation analysis
omega_num_exp &lt;- omega %&gt;% 
mutate(gender_01 = ifelse(gender==&#39;male&#39;, 1, 0)) %&gt;% # convert gender to numerical variable
select(gender_01, experience, salary) # select certain columns

omega_num_exp %&gt;%
select(gender_01, experience) %&gt;%
cor()</code></pre>
<pre><code>##            gender_01 experience
## gender_01      1.000      0.584
## experience     0.584      1.000</code></pre>
<p>Correlation coefficient of 0.584 indicates moderate correlation between gender and experience.</p>
<pre class="r"><code># Regression
lm_omega_2 &lt;- lm(formula = experience ~ gender_01, data = omega_num_exp) # run a linear regression of experience on gender
summary(lm_omega_2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = experience ~ gender_01, data = omega_num_exp)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -20.12  -6.32  -2.25   8.37  22.88 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     7.38       1.91    3.87  0.00033 ***
## gender_01      13.74       2.76    4.98  8.5e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 9.74 on 48 degrees of freedom
## Multiple R-squared:  0.341,  Adjusted R-squared:  0.327 
## F-statistic: 24.8 on 1 and 48 DF,  p-value: 8.51e-06</code></pre>
<p>Base on the R-squared value, we can say that 32% of variation in experience is explained by variation in gender. If a person is male instead of a female, the mean experience is expected to be 13.74 years more (statistically significant), all else equal. I think this analysis might endanger the results of previous analyses because if experience varies a lot between genders, it might be that variation in salaries is actually explained by variation in experience and when we don’t include experience into the model, it captures partial effect through gender (omitted variable bias).</p>
<p>We can make a multiple regression model.</p>
<pre class="r"><code># Regression
lm_omega_2 &lt;- lm(formula = salary ~ gender_01 + experience, data = omega_num_exp) # run a linear regression of experience on gender
summary(lm_omega_2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = salary ~ gender_01 + experience, data = omega_num_exp)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -13382  -3169   1100   3137  11521 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  60414.1     1176.3   51.36   &lt;2e-16 ***
## gender_01     1014.1     1826.4    0.56     0.58    
## experience     559.1       77.6    7.20    4e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5240 on 47 degrees of freedom
## Multiple R-squared:  0.647,  Adjusted R-squared:  0.632 
## F-statistic: 43.1 on 2 and 47 DF,  p-value: 2.3e-11</code></pre>
<p>From this model we can see that when we include both experience and gender as independent variables, gender coefficient is not statistically significant but the coefficient for experience is. So when we omit the experience from the model, gender coefficient becomes sginificant while in reality it is not.</p>
</div>
<div id="relationship-salary---experience" class="section level2">
<h2>Relationship Salary - Experience ?</h2>
<p>Someone at the meeting argues that clearly, a more thorough analysis of the relationship between salary and experience is required before any conclusion can be drawn about whether there is any gender-based salary discrimination in the company.</p>
<p>Analyse the relationship between salary and experience. Draw a scatterplot to visually inspect the data</p>
<pre class="r"><code>ggplot(data = omega, aes(x = experience, y = salary))+
  geom_point(alpha=0.3) +
  geom_smooth(method = &quot;lm&quot;) + 
  theme_bw() +
  labs(title = &quot;Relationship between salary and experience&quot;, x = &quot;Experience in years&quot;, y=&quot;Yearly salary in $&quot;)</code></pre>
<p><img src="/blogs/homework3_files/figure-html/salary_exp_scatter-1.png" width="648" style="display: block; margin: auto;" />
It seems like there is a positive relationship between experience and salary.</p>
<pre class="r"><code># Regression
lm_omega_2 &lt;- lm(formula = salary ~ experience, data = omega_num_exp) # run a linear regression of experience on gender
summary(lm_omega_2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = salary ~ experience, data = omega_num_exp)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -13516  -2926    634   2952  11997 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  60549.0     1142.6   52.99  &lt; 2e-16 ***
## experience     584.3       62.6    9.34  2.3e-12 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5200 on 48 degrees of freedom
## Multiple R-squared:  0.645,  Adjusted R-squared:  0.638 
## F-statistic: 87.2 on 1 and 48 DF,  p-value: 2.26e-12</code></pre>
<p>The regression model confirms strong positive relationship as well. On average, additional year of experience increases yearly salary by $584.</p>
</div>
<div id="check-correlations-between-the-data" class="section level2">
<h2>Check correlations between the data</h2>
<p>You can use <code>GGally:ggpairs()</code> to create a scatterplot and correlation matrix. Essentially, we change the order our variables will appear in and have the dependent variable (Y), salary, as last in our list. We then pipe the dataframe to <code>ggpairs()</code> with <code>aes</code> arguments to colour by <code>gender</code> and make ths plots somewhat transparent (<code>alpha  = 0.3</code>).</p>
<pre class="r"><code>omega %&gt;% 
  select(gender, experience, salary) %&gt;% #order variables they will appear in ggpairs()
  ggpairs(aes(colour=gender, alpha = 0.3))+
  theme_bw()</code></pre>
<p><img src="/blogs/homework3_files/figure-html/ggpairs-1.png" width="648" style="display: block; margin: auto;" /></p>
<blockquote>
<p>Look at the salary vs experience scatterplot. What can you infer from this plot? Explain in a couple of sentences</p>
</blockquote>
<p>We see a positive correlation between salary and experience. The reason why we initially thought there was pay discrimination is because, on average, women have less experience (more pink dots on the left) and men have more (more blue dots on the right).</p>
</div>
</div>
<div id="challenge-1-brexit-plot" class="section level1">
<h1>Challenge 1: Brexit plot</h1>
<p>Using your data manipulation and visualisation skills, please use the Brexit results dataframe (the same dataset you used in the pre-programme assignement) and produce the following plot. Use the correct colour for each party; google “UK Political Party Web Colours” and find the appropriate hex code for colours, not the default colours that R gives you.</p>
<pre class="r"><code>brexit_results &lt;- read_csv(&quot;https://raw.githubusercontent.com/kostis-christodoulou/am01/master/data/brexit_results.csv&quot;)
#Create vector withe the correct color for each party
party_colors &lt;- c(&quot;con_2015&quot; = &quot;#0087DC&quot;, &quot;lab_2015&quot; = &quot;#DC241f&quot;, &quot;ld_2015&quot; = &quot;#FDBB30&quot;,&quot;ukip_2015&quot;= &quot;#6D3177&quot;)

#Convert long to wide data
long_brexit_results &lt;- brexit_results %&gt;% 
  pivot_longer(cols=c(con_2015, lab_2015, ld_2015, ukip_2015), #select party columns
               names_to = &#39;party&#39;,  #name of the new column
               values_to = &#39;percent&#39;) %&gt;% 
 group_by(party)  #group by party

#Plot the data
ggplot(long_brexit_results) +
  aes(x = percent, y = leave_share, color = party) +
  geom_point(alpha = 0.3) +
  theme_bw() +
  theme(legend.position=&quot;bottom&quot;) +  #position legend at the bottom
  geom_smooth(method = &quot;lm&quot;) +   #add trend lines
  scale_color_manual(values = party_colors,  #assign custom color to each party 
                     labels = c(&quot;Conservative&quot;, &quot;Labour&quot;, &quot;Lib Dems&quot;, &quot;UKIP&quot;),  #change labels of the legend variable names
                     name = &quot;&quot;) +  #hide legend title
  labs(title = &quot;How political affiliation translated to Brexit Voting&quot;,
              x = &quot;Party % in the UK 2015 general election&quot;,
              y = &quot;Leave % in the 2016 Brexit referendum&quot;)</code></pre>
<p><img src="/blogs/homework3_files/figure-html/unnamed-chunk-14-1.png" width="648" style="display: block; margin: auto;" /></p>
</div>
<div id="challenge-2gdp-components-over-time-and-among-countries" class="section level1">
<h1>Challenge 2:GDP components over time and among countries</h1>
<p>At the risk of oversimplifying things, the main components of gross domestic product, GDP are personal consumption (C), business investment (I), government spending (G) and net exports (exports - imports). You can read more about GDP and the different approaches in calculating at the <a href="https://en.wikipedia.org/wiki/Gross_domestic_product">Wikipedia GDP page</a>.</p>
<p>The GDP data we will look at is from the <a href="https://unstats.un.org/unsd/snaama/Downloads">United Nations’ National Accounts Main Aggregates Database</a>, which contains estimates of total GDP and its components for all countries from 1970 to today. We will look at how GDP and its components have changed over time, and compare different countries and how much each component contributes to that country’s GDP. The file we will work with is <a href="http://unstats.un.org/unsd/amaapi/api/file/6">GDP and its breakdown at constant 2010 prices in US Dollars</a> and it has already been saved in the Data directory. Have a look at the Excel file to see how it is structured and organised</p>
<pre class="r"><code>UN_GDP_data  &lt;-  read_excel(here::here(&quot;data&quot;, &quot;Download-GDPconstant-USD-countries.xls&quot;), # Excel filename
                sheet=&quot;Download-GDPconstant-USD-countr&quot;, # Sheet name
                skip=2) # Number of rows to skip</code></pre>
<p>The first thing you need to do is to tidy the data, as it is in wide format and you must make it into long, tidy format. Please express all figures in billions (divide values by <code>1e9</code>, or <span class="math inline">\(10^9\)</span>), and you want to rename the indicators into something shorter.</p>
<blockquote>
<p>make sure you remove <code>eval=FALSE</code> from the next chunk of R code– I have it there so I could knit the document</p>
</blockquote>
<pre class="r"><code>tidy_GDP_data  &lt;-  UN_GDP_data %&gt;% 
  gather(key = year, value = GDP, &#39;1970&#39;:&#39;2017&#39;) %&gt;% 
  mutate(GDP_in_billion = GDP / 1e9) %&gt;% 
  subset(select = -GDP)

glimpse(tidy_GDP_data)</code></pre>
<pre><code>## Rows: 176,880
## Columns: 5
## $ CountryID      &lt;dbl&gt; 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 8, 8, 8…
## $ Country        &lt;chr&gt; &quot;Afghanistan&quot;, &quot;Afghanistan&quot;, &quot;Afghanistan&quot;, &quot;Afghanist…
## $ IndicatorName  &lt;chr&gt; &quot;Final consumption expenditure&quot;, &quot;Household consumption…
## $ year           &lt;chr&gt; &quot;1970&quot;, &quot;1970&quot;, &quot;1970&quot;, &quot;1970&quot;, &quot;1970&quot;, &quot;1970&quot;, &quot;1970&quot;,…
## $ GDP_in_billion &lt;dbl&gt; 5.559, 5.065, 0.372, 0.985, 0.985, 0.112, 0.184, 10.721…</code></pre>
<pre class="r"><code># Let us compare GDP components for these 3 countries
country_list &lt;- c(&quot;United States&quot;,&quot;India&quot;, &quot;Germany&quot;)

component_list &lt;- c(&quot;Gross capital formation&quot;,
                    &quot;Exports of goods and services&quot;,
                    &quot;Household consumption expenditure (including Non-profit institutions serving households)&quot;,
                    &quot;General government final consumption expenditure&quot;,
                    &quot;Imports of goods and services&quot;)

GDP_of_country_list &lt;- tidy_GDP_data %&gt;% 
  filter(Country %in% country_list) %&gt;% 
  filter(IndicatorName %in% component_list) %&gt;% 
  mutate(component = case_when(IndicatorName == &quot;Gross capital formation&quot; ~ &quot;Gross capital formation&quot;,
                               IndicatorName == &quot;Exports of goods and services&quot; ~ &quot;Exports&quot;,
                               IndicatorName == &quot;Household consumption expenditure (including Non-profit institutions serving households)&quot; ~ &quot;Household expenditure&quot;,
                               IndicatorName == &quot;General government final consumption expenditure&quot; ~ &quot;Government expenditure&quot;,
                               IndicatorName == &quot;Imports of goods and services&quot; ~ &quot;Imports&quot;)) %&gt;% 
  subset(select = -IndicatorName)</code></pre>
<p>First, can you produce this plot?</p>
<pre class="r"><code>GDP_of_country_list %&gt;% 
  ggplot(aes(x = year, y = GDP_in_billion, color = component, group = component)) +
  geom_line() +
  facet_wrap(~ Country) +
  scale_x_discrete(breaks = seq(1970, 2010, 10)) +
  labs(x = NULL, y = &quot;Billion US$&quot;,
       title = &quot;GDP components over time&quot;,
       subtitle = &quot;in constant 2010 USD&quot;)</code></pre>
<p><img src="/blogs/homework3_files/figure-html/unnamed-chunk-15-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>Secondly, recall that GDP is the sum of Household Expenditure (Consumption <em>C</em>), Gross Capital Formation (business investment <em>I</em>), Government Expenditure (G) and Net Exports (exports - imports). Even though there is an indicator <code>Gross Domestic Product (GDP)</code> in your dataframe, I would like you to calculate it given its components discussed above.</p>
<blockquote>
<p>What is the % difference between what you calculated as GDP and the GDP figure included in the dataframe?</p>
</blockquote>
<blockquote>
<p>The % difference between what I calculated as GDP and the GDP figure included in the dataframe is 0.87%.</p>
</blockquote>
<pre class="r"><code>Diff_component_list &lt;- c(&quot;Gross capital formation&quot;,
                    &quot;Exports of goods and services&quot;,
                    &quot;Household consumption expenditure (including Non-profit institutions serving households)&quot;,
                    &quot;General government final consumption expenditure&quot;,
                    &quot;Imports of goods and services&quot;,
                    &quot;Gross Domestic Product (GDP)&quot;)

GDP_difference &lt;- tidy_GDP_data %&gt;% 
  filter(Country %in% country_list) %&gt;% 
  filter(IndicatorName %in% Diff_component_list) %&gt;% 
  mutate(component = case_when(IndicatorName == &quot;Gross capital formation&quot; ~ &quot;Gross_capital_formation&quot;,
                               IndicatorName == &quot;Exports of goods and services&quot; ~ &quot;Exports&quot;,
                               IndicatorName == &quot;Household consumption expenditure (including Non-profit institutions serving households)&quot; ~ &quot;Household_expenditure&quot;,
                               IndicatorName == &quot;General government final consumption expenditure&quot; ~ &quot;Government_expenditure&quot;,
                               IndicatorName == &quot;Imports of goods and services&quot; ~ &quot;Imports&quot;,
                               IndicatorName == &quot;Gross Domestic Product (GDP)&quot; ~ &quot;GDP&quot;)) %&gt;% 
  subset(select = -IndicatorName) %&gt;% 
  pivot_wider(names_from = component, values_from = GDP_in_billion, values_fill = 0) %&gt;% 
  mutate(CountryID = CountryID,
         Country = Country,
         new_GDP = Gross_capital_formation + Household_expenditure + Government_expenditure + Exports - Imports,
         Net_Exports = (Exports - Imports) / new_GDP,
         Gross_capital_formation = Gross_capital_formation / new_GDP,
         Household_expenditure = Household_expenditure / new_GDP,
         Government_expenditure = Government_expenditure / new_GDP,
         GDP_diff = ((new_GDP / GDP) - 1)
        ) %&gt;% 
  select(-Imports, -Exports, -GDP, -new_GDP)

mean(GDP_difference$GDP_diff, na.rm = FALSE)</code></pre>
<pre><code>## [1] 0.00867</code></pre>
<pre class="r"><code>GDP_breakdown_propotion &lt;- GDP_difference %&gt;%
  select(-GDP_diff) %&gt;% 
  pivot_longer(4:7, names_to = &quot;component&quot;, values_to = &quot;proportion&quot;) 

GDP_breakdown_propotion %&gt;% 
  ggplot(aes(x = year, y = proportion, color = component, group = component)) +
  geom_line() +
  facet_wrap(~ Country) +
  scale_x_discrete(breaks = seq(1970, 2010, 10)) +
  scale_y_continuous(labels = scales::percent)</code></pre>
<p><img src="/blogs/homework3_files/figure-html/unnamed-chunk-17-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>  labs(x = NULL, y = &quot;proportion&quot;,
       title = &quot;GDP and its breakdown at constant 2010 prices in US Dollars&quot;,
       subtitle = &quot;in constant 2010 USD&quot;,
       caption = &quot;Source: United Nations, https://unstats.un.org/unsd/snaama/Downloads&quot;)</code></pre>
<pre><code>## $x
## NULL
## 
## $y
## [1] &quot;proportion&quot;
## 
## $title
## [1] &quot;GDP and its breakdown at constant 2010 prices in US Dollars&quot;
## 
## $subtitle
## [1] &quot;in constant 2010 USD&quot;
## 
## $caption
## [1] &quot;Source: United Nations, https://unstats.un.org/unsd/snaama/Downloads&quot;
## 
## attr(,&quot;class&quot;)
## [1] &quot;labels&quot;</code></pre>
<blockquote>
<p>What is this last chart telling you? Can you explain in a couple of paragraphs the different dynamic among these three countries?</p>
</blockquote>
<blockquote>
<p>Since all three countries we study have experienced overall positive GDP growth over the last 50 years, we can see from the graph that the composition of GDP is very different in each country. The United States has experienced rapid growth in household spending and a decline in government spending, suggesting that most U.S. households have become wealthier and the economy is less dependent on government spending. Germany has experienced stable household spending over the years, but growing exports, suggesting that Germany has a huge advantage in manufacturing, which is recognized worldwide. India, however, has seen a rapid decline in household spending. Although the Indian economy has grown statistically, it is not healthy or sustainable. It is heavily dependent on gross capital formation.</p>
</blockquote>
</div>
<div id="details" class="section level1">
<h1>Details</h1>
<ul>
<li>Who did you collaborate with: Ioana-Daria Gherghelas, Sophia Lyuleva, Sneha Ramteke, Arvind Sridhar, Sihan Lu, Wei Wu</li>
<li>Approximately how much time did you spend on this problem set: One day.</li>
<li>What, if anything, gave you the most trouble:</li>
</ul>
</div>
